<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Droppable</name>
   <tag></tag>
   <elementGuidId>65d79957-f156-44ad-9e70-0b294dbe676c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar']/aside/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'http://jqueryui.com/droppable/' and (text() = 'Droppable' or . = 'Droppable')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36dee859-3c14-4345-b93b-3d4f33526f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://jqueryui.com/droppable/</value>
      <webElementGuid>7ee32742-50c4-4478-bea2-ba946f7887db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Droppable</value>
      <webElementGuid>d0db750c-e974-43d0-a0c1-2c487b1e6c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/aside[@class=&quot;widget&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>5231c188-cc7e-433c-84ae-34e716d89552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar']/aside/ul/li[2]/a</value>
      <webElementGuid>d3c8e851-61ac-48a7-9c8f-b676548ef551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Droppable')]</value>
      <webElementGuid>3d0be9b1-6c26-490c-b535-d82a039f89c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draggable'])[1]/following::a[1]</value>
      <webElementGuid>ff08a46b-16d5-4b4e-b4fd-dc341f7206ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interactions'])[1]/following::a[2]</value>
      <webElementGuid>a9921a04-9150-43d8-996e-f8db15d85274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resizable'])[1]/preceding::a[1]</value>
      <webElementGuid>a3eb399c-36bc-4cd7-b7dc-6b84fd284961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selectable'])[1]/preceding::a[2]</value>
      <webElementGuid>0e377a25-4321-41f7-ab0f-1eadd407206f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Droppable']/parent::*</value>
      <webElementGuid>c27dc85a-99d9-4f82-b5cd-70ad49b86de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://jqueryui.com/droppable/']</value>
      <webElementGuid>0e18768c-8301-409b-bee4-a696406b3ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/ul/li[2]/a</value>
      <webElementGuid>04bc9136-ad70-4e79-be1a-f3391ae95ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://jqueryui.com/droppable/' and (text() = 'Droppable' or . = 'Droppable')]</value>
      <webElementGuid>a490e617-8bd6-41bb-b4da-2cd2a60d1887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
